# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class CommonServiceStub(object):
  """Define Common Service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.handle = channel.unary_unary(
        '/CommonService/handle',
        request_serializer=service__pb2.Request.SerializeToString,
        response_deserializer=service__pb2.Response.FromString,
        )


class CommonServiceServicer(object):
  """Define Common Service
  """

  def handle(self, request, context):
    """common rpc function
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommonServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'handle': grpc.unary_unary_rpc_method_handler(
          servicer.handle,
          request_deserializer=service__pb2.Request.FromString,
          response_serializer=service__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CommonService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
